const Store = require('electron-store')
const store = new Store();
store.clear()
store.set('running', {streak:[]})
store.set('gym', {streak:[]})
store.set('read', {streak:[]})
store.set('water', {streak:[]})
store.set('lifting', {streak:[]})
store.set('french', {streak:[]})
store.set('typing', {streak:[]})
store.set('git', {streak:[]})
store.set('commitingt', {streak:[]})
store.set('hello', {streak:[]})
console.log(store.store)
